apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /kubernetes101/mntDir  # <-- Local directory on the node
  persistentVolumeReclaimPolicy: Retain